version: 0.1.{build}
branches:
  only:
  - master
configuration: Release
build_script:
- cmd: >-
    dotnet restore

    dotnet build **/project.json

    dotnet pack CloudDotNet
test_script:
- cmd: dotnet test CloudDotNet.Tests.Unit\
artifacts:
- path: CloudDotNet\bin\Debug\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 5+SUZKFkrKpiGjy/Kv2igz+SC8vio1U5xVWRsQRVKqXgehgmTe/5SXBXlcFZsykJ
  skip_symbols: false
  artifact: nuget